FROM docker.elastic.co/beats/filebeat:8.13.0

USER root

# Копируем конфиг
COPY filebeat.yml /usr/share/filebeat/filebeat.yml
COPY wait-for-elasticsearch.sh /wait-for-elasticsearch.sh

# Разрешаем выполнение скрипта
RUN chmod +x /wait-for-elasticsearch.sh \
    && chown root:filebeat /usr/share/filebeat/filebeat.yml \
    && chmod 600 /usr/share/filebeat/filebeat.yml


ENTRYPOINT ["/wait-for-elasticsearch.sh"]
