version: '3.8'

volumes:
  grafana-data:
  m2-volume:


services:

  api-app:
    build:
      context: .               # Путь к папке с Dockerfile твоего Spring Boot приложения
      dockerfile: Dockerfile   # Имя Dockerfile (если отличается - поправь)
    image: api-app:latest  # Можно оставить для тега образа
    ports:
      - "8092:8092"
    environment:
      SPRING_PROFILES_ACTIVE: test   # если используешь профили (необязательно)
    volumes:
      - m2-volume:/root/.m2


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api-app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SMTP_USER: ${GF_SMTP_USER}
      GF_SMTP_PASSWORD: ${GF_SMTP_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./config/grafana-config/grafana.ini:/etc/grafana/grafana.ini:ro   # монтируем конфиг внутрь контейнера
    depends_on:
      - prometheus



