server:
  port: 8092  # Порт приложения (не базы!)
  servlet:
    context-path: /property-view

spring:
  application:
    name: api-app
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_empty

  liquibase:
    change-log: classpath:db/changelog/db.changelog-hotels.xml
    enabled: true

  datasource:
    url: jdbc:h2:mem:hoteldb
#    url: jdbc:h2:file:~/data/hoteldb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_schema: PUBLIC

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    liquibase: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui
