global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'hotel-service'
    metrics_path: '/property-view/actuator/prometheus'
    static_configs:
      - targets: ['api-app:8092']
  - job_name: 'histogram-service'
    metrics_path: '/property-view/histogram/brand'
    static_configs:
      - targets: ['api-app:8092']
  - job_name: 'search-service'
    metrics_path: '/property-view/search'
    static_configs:
      - targets: ['api-app:8092']

  - job_name: 'histogram-service_error'
    metrics_path: '/property-view/Gistogram/brand'
    static_configs:
      - targets: ['api-app:8092']